### ISSUE TITLE
No active links to technologies

### ISSUE THREAD

**Issue by arjunsinghy96** [vijaykrishnavanshi/til#1]
## Problem:
There are no active links to the technologies mentioned in the write-ups.
#### Example:
 [Benchmark Tools](https://github.com/vijaykrishnavanshi/til/blob/master/server/tools-to-benchmark-apis-performance.md) have no link to **vegeta** and **wrk**

## Expected Behaviour
Technologies should contain a link to docs or homepage for at least their first occurrence.

**Comment by vijaykrishnavanshi** [comment]
Addressed this issue in recent commits.
